kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dmf/Projects"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cr-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
