version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Configure Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - type: shell
        name: Build and Ship ZSH Image
        command: |
          cd containers/zsh
          docker build -t davefinster/zsh:${CIRCLE_BRANCH} .
          docker push davefinster/zsh:${CIRCLE_BRANCH}
      - type: shell
        name: Build and Ship emacs Image
        command: |
          cd containers/emacs
          docker build -t davefinster/emacs:${CIRCLE_BRANCH} .
          docker push davefinster/emacs:${CIRCLE_BRANCH}
      - type: shell
        name: Build and Ship golang Image
        command: |
          cd containers/golang
          docker build -t davefinster/golang:${CIRCLE_BRANCH} .
          docker push davefinster/golang:${CIRCLE_BRANCH}
      - type: shell
        name: Build and Ship typescript Image
        command: |
          cd containers/typescript
          docker build -t davefinster/typescript:${CIRCLE_BRANCH} .
          docker push davefinster/typescript:${CIRCLE_BRANCH}
